### ISSUE TITLE
CSS file strangely not included in `compilation.assets`

### ISSUE THREAD

**Issue by isellsoap** [sueddeutsche/stats-replace-webpack-plugin#1]
I can’t replace a CSS file with the plugin. The output of the build is:

![bildschirmfoto 2016-10-20 um 17 35 51](https://cloud.githubusercontent.com/assets/477474/19566783/c5b15c8a-96eb-11e6-8efd-0872a9b6642a.png)

As you can see above I added a DEBUG statement inside of the plugin:

![bildschirmfoto 2016-10-20 um 17 37 09](https://cloud.githubusercontent.com/assets/477474/19566808/e2299332-96eb-11e6-939e-ecd45190e5c2.png)

Why isn’t the CSS file included in `assetNames` of the plugin, but webpack lists it as a normally emitted asset (green text, last line)?

**Comment by isellsoap** [comment]
Ah, I think the problem is that the CSS file is being generated through the extract-text-webpack-plugin.

**Comment by isellsoap** [comment]
Fixed with https://github.com/sueddeutsche/stats-replace-webpack-plugin/commit/2fc5250b33926281908b13600e5379c0f6b130d5. Thanks, @benurb!

**Comment by benurb** [comment]
No problem 😄
